apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
spec:
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            subPath: demo
            name: static-website-volume
      volumes:
        - name: static-website-volume
          gitRepo:
            repository: https://github.com/cpablo-demo/demo.git
